# Generated by Django 4.1.7 on 2023-03-13 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_flags_svg_flags_flag_base64'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=64)),
                ('de_name', models.CharField(max_length=64)),
                ('es_name', models.CharField(max_length=64)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.flags')),
            ],
        ),
    ]
