# Generated by Django 4.1.7 on 2023-03-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='translations',
            old_name='name',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='translations',
            old_name='de_name',
            new_name='translated_country_name',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='flags',
            name='name',
        ),
        migrations.RemoveField(
            model_name='translations',
            name='en_name',
        ),
        migrations.RemoveField(
            model_name='translations',
            name='es_name',
        ),
        migrations.AddField(
            model_name='audio',
            name='country_name',
            field=models.ManyToManyField(to='quiz.flags'),
        ),
        migrations.AddField(
            model_name='flags',
            name='continent',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='flags',
            name='country_name',
            field=models.CharField(default='', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.AddField(
            model_name='audio',
            name='language',
            field=models.ManyToManyField(to='quiz.language'),
        ),
        migrations.AddField(
            model_name='translations',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quiz.language'),
            preserve_default=False,
        ),
    ]
