# Generated by Django 4.1.7 on 2023-03-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_language_rename_name_translations_country_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flags',
            old_name='country_name',
            new_name='description',
        ),
    ]
