# Generated by Django 4.1.7 on 2023-03-24 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_translations_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('continent', models.ManyToManyField(to='quiz.continent')),
            ],
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='language',
        ),
        migrations.RemoveField(
            model_name='flags',
            name='continent',
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.BinaryField(null=True),
        ),
        migrations.RemoveField(
            model_name='audio',
            name='country_name',
        ),
        migrations.DeleteModel(
            name='Translations',
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.flags'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.language'),
        ),
        migrations.AddField(
            model_name='audio',
            name='country_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.country'),
        ),
    ]
