# Generated by Django 4.1.7 on 2023-03-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_continent_country_rename_language_code_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
