# Generated by Django 4.1.7 on 2023-03-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_continent_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('name', 'name_language')},
        ),
    ]
