# Generated by Django 4.1.7 on 2023-03-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_country_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(models.F('name'), models.F('name_language'), name='name_language_unique'),
        ),
    ]
